/**
 * @file        rex/ui/window_ios.mm
 * @brief       iOS/iPadOS backend for rex::ui::Window (UIKit + CAMetalLayer)
 *
 * Follows the structure of window_macos.mm with the pieces that have no iPad
 * equivalent removed: no resizable window, no menus, no cursor capture, no
 * runtime fullscreen transitions (the window always covers the screen), and
 * no keyboard/mouse events (input is physical game controllers via SDL3).
 */

#include <rex/platform.h>
#if REX_PLATFORM_IOS

#include <rex/ui/window.h>

#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#import <UIKit/UIKit.h>

#include <atomic>
#include <cmath>
#include <memory>
#include <string_view>

#include <rex/ui/surface_macos.h>

namespace rex::ui {
class IOSWindow;
}  // namespace rex::ui

// UIView whose backing layer is the CAMetalLayer the presenter draws into.
@interface RexIOSMetalView : UIView {
 @private
  rex::ui::IOSWindow* owner_;
}
- (instancetype)initWithFrame:(CGRect)frame owner:(rex::ui::IOSWindow*)owner;
- (void)detachOwner;
@end

// CADisplayLink target pumping coalesced paint requests once per vsync,
// mirroring the windowDidUpdate: pump of the manual AppKit loop on macOS.
@interface RexIOSDisplayLinkTarget : NSObject {
 @private
  rex::ui::IOSWindow* owner_;
}
- (instancetype)initWithOwner:(rex::ui::IOSWindow*)owner;
- (void)detachOwner;
- (void)tick:(CADisplayLink*)link;
@end

@interface RexIOSViewController : UIViewController
@end

namespace rex::ui {

class IOSWindow final : public Window {
 public:
  IOSWindow(WindowedAppContext& app_context, std::string_view title,
            uint32_t desired_logical_width, uint32_t desired_logical_height)
      : Window(app_context, title, desired_logical_width, desired_logical_height) {}

  ~IOSWindow() override {
    EnterDestructor();
    CloseNative();
  }

  void HandleResize() {
    if (!ui_window_) {
      return;
    }
    UpdateDrawableSize();
    WindowDestructionReceiver destruction_receiver(this);
    UpdateActualSize(destruction_receiver);
  }

  void HandlePendingPaint() {
    // Clear the request before painting so a request generated by an ImGui
    // drawer during this paint remains set for the next display link tick.
    if (paint_requested_.exchange(false, std::memory_order_acq_rel)) {
      OnPaint(true);
    }
  }

 protected:
  bool OpenImpl() override {
    id<MTLDevice> device = MTLCreateSystemDefaultDevice();
    if (!device) {
      return false;
    }

    UIScreen* screen = [UIScreen mainScreen];
    ui_window_ = [[UIWindow alloc] initWithFrame:[screen bounds]];

    // Inside a scene-based host process (e.g. LiveContainer) a window that is
    // not attached to a UIWindowScene never becomes visible. Standalone, this
    // app uses the delegate lifecycle and has no connected scenes - harmless.
    for (UIScene* scene in [[UIApplication sharedApplication] connectedScenes]) {
      if ([scene isKindOfClass:[UIWindowScene class]]) {
        [ui_window_ setWindowScene:(UIWindowScene*)scene];
        break;
      }
    }

    RexIOSMetalView* view = [[RexIOSMetalView alloc] initWithFrame:[screen bounds] owner:this];
    metal_layer_ = (CAMetalLayer*)[view layer];
    [metal_layer_ retain];
    [metal_layer_ setDevice:device];
    [metal_layer_ setPixelFormat:MTLPixelFormatBGRA8Unorm];
    [metal_layer_ setFramebufferOnly:YES];
    [device release];

    RexIOSViewController* view_controller = [[RexIOSViewController alloc] init];
    [view_controller setView:view];
    [view release];
    [ui_window_ setRootViewController:view_controller];
    [view_controller release];
    [ui_window_ makeKeyAndVisible];

    display_link_target_ = [[RexIOSDisplayLinkTarget alloc] initWithOwner:this];
    display_link_ = [CADisplayLink displayLinkWithTarget:display_link_target_
                                                selector:@selector(tick:)];
    [display_link_ addToRunLoop:[NSRunLoop mainRunLoop] forMode:NSRunLoopCommonModes];

    UpdateDrawableSize();

    WindowDestructionReceiver destruction_receiver(this);
    UpdateActualSize(destruction_receiver);
    if (!destruction_receiver.IsWindowDestroyedOrClosed()) {
      OnFocusUpdate(true, destruction_receiver);
    }
    return !destruction_receiver.IsWindowDestroyedOrClosed();
  }

  void RequestCloseImpl() override {
    WindowDestructionReceiver destruction_receiver(this);
    OnBeforeClose(destruction_receiver);
    if (destruction_receiver.IsWindowDestroyed()) {
      return;
    }
    CloseNative();
    OnAfterClose();
  }

  std::unique_ptr<Surface> CreateSurfaceImpl(Surface::TypeFlags allowed_types) override {
    if (!(allowed_types & Surface::kTypeFlag_CAMetalLayer) || !metal_layer_) {
      return nullptr;
    }
    return std::make_unique<MacOSMetalLayerSurface>((void*)metal_layer_);
  }

  void RequestPaintImpl() override {
    paint_requested_.store(true, std::memory_order_release);
  }

  uint32_t GetLatestDpiImpl() const override {
    UIScreen* screen = ui_window_ ? [ui_window_ screen] : [UIScreen mainScreen];
    CGFloat scale = screen ? [screen scale] : 1.0;
    return static_cast<uint32_t>(96.0 * scale);
  }

  // The window always covers the screen; runtime fullscreen toggles, mouse
  // capture and menus intentionally keep the Window base defaults.

 private:
  void CloseNative() {
    if (display_link_) {
      [display_link_ invalidate];
      display_link_ = nil;
    }
    if (display_link_target_) {
      [display_link_target_ detachOwner];
      [display_link_target_ release];
      display_link_target_ = nil;
    }
    if (ui_window_) {
      RexIOSMetalView* view = (RexIOSMetalView*)[[ui_window_ rootViewController] view];
      [view detachOwner];
      [ui_window_ setHidden:YES];
      [ui_window_ release];
      ui_window_ = nil;
    }
    if (metal_layer_) {
      [metal_layer_ release];
      metal_layer_ = nil;
    }
  }

  void UpdateDrawableSize() {
    if (!ui_window_ || !metal_layer_) {
      return;
    }
    UIView* view = [[ui_window_ rootViewController] view];
    const CGFloat scale = [ui_window_ screen] ? [[ui_window_ screen] scale] : 1.0;
    const CGRect bounds = [view bounds];
    [metal_layer_ setContentsScale:scale];
    [metal_layer_ setDrawableSize:CGSizeMake(bounds.size.width * scale,
                                             bounds.size.height * scale)];
  }

  void UpdateActualSize(WindowDestructionReceiver& destruction_receiver) {
    if (!ui_window_) {
      return;
    }
    const CGSize drawable = [metal_layer_ drawableSize];
    OnActualSizeUpdate(
        drawable.width > 0.0 ? static_cast<uint32_t>(std::lround(drawable.width)) : 0,
        drawable.height > 0.0 ? static_cast<uint32_t>(std::lround(drawable.height)) : 0,
        destruction_receiver);
  }

  UIWindow* ui_window_ = nil;
  CAMetalLayer* metal_layer_ = nil;
  CADisplayLink* display_link_ = nil;
  RexIOSDisplayLinkTarget* display_link_target_ = nil;
  std::atomic<bool> paint_requested_{false};
};

std::unique_ptr<Window> Window::Create(WindowedAppContext& app_context, std::string_view title,
                                       uint32_t desired_logical_width,
                                       uint32_t desired_logical_height) {
  return std::make_unique<IOSWindow>(app_context, title, desired_logical_width,
                                     desired_logical_height);
}

}  // namespace rex::ui

@implementation RexIOSMetalView

+ (Class)layerClass {
  return [CAMetalLayer class];
}

- (instancetype)initWithFrame:(CGRect)frame owner:(rex::ui::IOSWindow*)owner {
  self = [super initWithFrame:frame];
  if (self) {
    owner_ = owner;
    [self setContentScaleFactor:[[UIScreen mainScreen] scale]];
  }
  return self;
}

- (void)detachOwner {
  owner_ = nullptr;
}

- (void)layoutSubviews {
  [super layoutSubviews];
  if (owner_) {
    owner_->HandleResize();
  }
}

@end

@implementation RexIOSDisplayLinkTarget

- (instancetype)initWithOwner:(rex::ui::IOSWindow*)owner {
  self = [super init];
  if (self) {
    owner_ = owner;
  }
  return self;
}

- (void)detachOwner {
  owner_ = nullptr;
}

- (void)tick:(CADisplayLink*)link {
  (void)link;
  if (owner_) {
    owner_->HandlePendingPaint();
  }
}

@end

@implementation RexIOSViewController

- (BOOL)prefersHomeIndicatorAutoHidden {
  return YES;
}

- (BOOL)prefersStatusBarHidden {
  return YES;
}

@end

#endif  // REX_PLATFORM_IOS
