/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2022 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 *
 * @modified    Tom Clay, 2026 - Adapted for ReXGlue runtime
 */

#pragma once

#include <atomic>
#include <chrono>
#include <cstring>
#include <functional>
#include <memory>
#include <mutex>
#include <queue>
#include <shared_mutex>
#include <string>
#include <unordered_map>
#include <vector>

#include <rex/graphics/command_ring_state.h>
#include <rex/graphics/register_file.h>
#include <rex/graphics/registers.h>
#include <rex/graphics/trace_writer.h>
#include <rex/graphics/xenos.h>
#include <rex/memory.h>
#include <rex/memory/ring_buffer.h>
#include <rex/system/xthread.h>
#include <rex/thread.h>
#include <rex/ui/presenter.h>

namespace rex::stream {
class ByteStream;
}  // namespace rex::stream

namespace rex::graphics {

class GraphicsSystem;
class Shader;

enum class ReadbackResolveMode {
  kDisabled,
  kFast,
  kSome,
  kFull,
};

struct SwapState {
  // Lock must be held when changing data in this structure.
  std::mutex mutex;
  // Dimensions of the framebuffer textures. Should match window size.
  uint32_t width = 0;
  uint32_t height = 0;
  // Current front buffer, being drawn to the screen.
  uintptr_t front_buffer_texture = 0;
  // Current back buffer, being updated by the CP.
  uintptr_t back_buffer_texture = 0;
  // Backend data
  void* backend_data = nullptr;
  // Whether the back buffer is dirty and a swap is pending.
  bool pending = false;
};

enum class SwapMode {
  kNormal,
  kIgnored,
};

enum class GammaRampType {
  kUnknown = 0,
  kTable,
  kPWL,
};

class CommandProcessor {
 public:
  enum class GpuCompletionMemoryWriteWaitResult {
    kUnavailable,
    kPending,
    kCompleted,
  };

  enum class WaitRegMemMemoryChangeResult {
    kUnavailable,
    kTimeout,
    kSignaled,
  };

  enum class SwapPostEffect {
    kNone,
    kFxaa,
    kFxaaExtreme,
  };

  CommandProcessor(GraphicsSystem* graphics_system, system::KernelState* kernel_state);
  virtual ~CommandProcessor();

  uint32_t counter() const { return counter_.load(std::memory_order_acquire); }
  void increment_counter() { counter_.fetch_add(1, std::memory_order_acq_rel); }
  uint32_t swap_counter() const { return swap_counter_.load(std::memory_order_acquire); }
  void increment_swap_counter() { swap_counter_.fetch_add(1, std::memory_order_acq_rel); }
  CommandRingState::Snapshot primary_ring_snapshot() const { return ring_state_.GetSnapshot(); }
  uint32_t read_ptr_index() const { return ring_state_.GetSnapshot().read_pointer; }
  uint32_t write_ptr_index() const { return ring_state_.GetSnapshot().write_pointer; }
  bool primary_ring_drained() const {
    const CommandRingState::Snapshot snapshot = ring_state_.GetSnapshot();
    return snapshot.configured && snapshot.write_pointer_valid() &&
           !snapshot.has_pending_commands();
  }

  Shader* active_vertex_shader() const { return active_vertex_shader_; }
  Shader* active_pixel_shader() const { return active_pixel_shader_; }

  virtual bool Initialize();
  virtual void Shutdown();

  // Returns false if shutdown has already stopped the worker and the function
  // could not be accepted.
  bool CallInThread(std::function<void()> fn);

  virtual void ClearCaches();
  virtual void InvalidateGpuMemory();

  // "Desired" is for the external thread managing the post-processing effect.
  SwapPostEffect GetDesiredSwapPostEffect() const { return swap_post_effect_desired_; }
  void SetDesiredSwapPostEffect(SwapPostEffect swap_post_effect);
  // Implementations must not make assumptions that the front buffer will
  // necessarily be a resolve destination - it may be a texture generated by any
  // means like written to by the CPU or loaded from a file (the disclaimer
  // screen right in the beginning of 4D530AA4 is not a resolved render target,
  // for instance).
  virtual void IssueSwap(uint32_t frontbuffer_ptr, uint32_t frontbuffer_width,
                         uint32_t frontbuffer_height) = 0;

  // May be called not only from the command processor thread when the command
  // processor is paused, and the termination of this function may be explicitly
  // awaited.
  virtual void InitializeShaderStorage(const std::filesystem::path& cache_root, uint32_t title_id,
                                       bool blocking);

  // The return value reports whether the worker accepted the control request,
  // not whether a capture file has already been opened or finalized.
  virtual bool RequestFrameTrace(const std::filesystem::path& root_path);
  virtual bool BeginTracing(const std::filesystem::path& root_path);
  virtual bool EndTracing();

  virtual void TracePlaybackWroteMemory(uint32_t base_ptr, uint32_t length) = 0;

  void RestoreRegisters(uint32_t first_register, const uint32_t* register_values,
                        uint32_t register_count, bool execute_callbacks);
  void RestoreGammaRamp(const reg::DC_LUT_30_COLOR* new_gamma_ramp_256_entry_table,
                        const reg::DC_LUT_PWL_DATA* new_gamma_ramp_pwl_rgb,
                        uint32_t new_gamma_ramp_rw_component);
  // Returns only after the backend has accepted the complete canonical image.
  // Trace playback treats false as fatal and will not produce capture output.
  virtual bool RestoreEdramSnapshot(const void* snapshot) = 0;

  void InitializeRingBuffer(uint32_t ptr, uint32_t size_log2);
  void EnableReadPointerWriteBack(uint32_t ptr, uint32_t block_size_log2);

  void UpdateWritePointer(uint32_t value);
  uint32_t ReadRingBufferRegister(uint32_t index) const;
  void WriteRingBufferRegister(uint32_t index, uint32_t value);

  // Executes the complete direct packet span with the existing backend
  // fail-soft policy, but reports whether every packet handler succeeded.
  // Live callers may ignore the result. Deterministic trace replay must not.
  bool ExecutePacket(uint32_t ptr, uint32_t count);
  // In addition to normal packet-handler failures, rejects packets that live
  // Metal gameplay intentionally skips (such as unimplemented Type 3 opcodes).
  bool ExecutePacketForTrace(uint32_t ptr, uint32_t count);

  // May be called by recompiled guest code immediately after a CPU memory
  // store. Backends use this as a precise, post-store wake hint for an active
  // WAIT_REG_MEM; the packet still re-reads and evaluates its own predicate.
  virtual void NotifyWaitRegMemMemoryWrite(uint32_t address, uint32_t length);

  bool is_paused() const { return paused_.load(std::memory_order_acquire); }
  void Pause();
  void Resume();

  bool Save(::rex::stream::ByteStream* stream);
  bool Restore(::rex::stream::ByteStream* stream);

 protected:
  enum class PacketExecutionMode {
    kLiveFailSoft,
    kTraceFailClosed,
  };

  struct IndexBufferInfo {
    xenos::IndexFormat format = xenos::IndexFormat::kInt16;
    xenos::Endian endianness = xenos::Endian::kNone;
    uint32_t count = 0;
    uint32_t guest_base = 0;
    size_t length = 0;
  };

  void WorkerThreadMain();
  bool HasPendingFunctions() const;
  bool TryPopPendingFunction(std::function<void()>* fn);
  virtual bool SetupContext() = 0;
  virtual void ShutdownContext() = 0;

  virtual void WriteRegister(uint32_t index, uint32_t value);
  // Writes memory as an operation performed by the emulated GPU. Backends may
  // override this to preserve host-GPU ordering for completion packets; the
  // default implementation writes the guest physical mapping immediately.
  virtual bool WriteGpuMemory(uint32_t address, const void* data, size_t length);
  // Completion writes are guest-visible fences, unlike ordinary packet memory
  // writes. Backends with deferred host-GPU work override this hook to publish
  // the value only after all earlier GPU work is complete.
  virtual bool WriteGpuCompletionMemory(uint32_t address, const void* data, size_t length);
  // Flushes completion writes deferred by a backend. Called before a
  // command-stream wait; backends may also flush at primary-ring boundaries.
  virtual bool FlushGpuCompletionMemoryWrites();
  uint32_t ReadRegisterValue(uint32_t index) const;
  virtual void WriteRegistersFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  virtual void WriteRegisterRangeFromRing(memory::RingBuffer* ring, uint32_t base,
                                          uint32_t num_registers);
  void WriteALURangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteFetchRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteBoolRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteLoopRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteREGISTERSRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteALURangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteFetchRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteBoolRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteLoopRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteREGISTERSRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);

  const reg::DC_LUT_30_COLOR* gamma_ramp_256_entry_table() const {
    return gamma_ramp_256_entry_table_;
  }
  const reg::DC_LUT_PWL_DATA* gamma_ramp_pwl_rgb() const { return gamma_ramp_pwl_rgb_[0]; }
  virtual void OnGammaRamp256EntryTableValueWritten() {}
  virtual void OnGammaRampPWLValueWritten() {}

  virtual void MakeCoherent();
  virtual void PrepareForWait();
  virtual void ReturnFromWait();
  // Gives a backend a bounded opportunity to sleep on the exact queued GPU
  // completion write rather than polling its guest-memory destination.
  virtual GpuCompletionMemoryWriteWaitResult WaitForGpuCompletionMemoryWrite(
      uint32_t address, uint32_t length, std::chrono::milliseconds timeout);
  // A backend may arm a notification for guest CPU writes to a WAIT_REG_MEM
  // destination before the packet's first authoritative read. Waiting is
  // always bounded by the caller and notifications are only hints: the packet
  // re-reads and evaluates its predicate after every wake or timeout.
  virtual bool BeginWaitRegMemMemoryChange(uint32_t address, uint32_t length);
  virtual WaitRegMemMemoryChangeResult WaitForWaitRegMemMemoryChange(
      std::chrono::milliseconds timeout);
  virtual void EndWaitRegMemMemoryChange();
  virtual void OnWaitRegMemComplete(bool, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t,
                                    uint32_t, uint32_t, uint64_t, uint64_t, bool, bool) {}

  uint32_t ExecutePrimaryBuffer(uint32_t start_index, uint32_t end_index,
                                uint32_t primary_buffer_ptr, uint32_t primary_buffer_size);
  virtual void OnPrimaryBufferEnd() {}
  bool ExecuteIndirectBuffer(uint32_t ptr, uint32_t length,
                             PacketExecutionMode mode = PacketExecutionMode::kLiveFailSoft);
  bool ExecutePacket(memory::RingBuffer* reader,
                     PacketExecutionMode mode = PacketExecutionMode::kLiveFailSoft);
  bool ExecutePacketType0(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType1(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType2(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType3(memory::RingBuffer* reader, uint32_t packet,
                          PacketExecutionMode mode);
  bool ExecutePacketType3_ME_INIT(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_NOP(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_INTERRUPT(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_XE_SWAP(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_INDIRECT_BUFFER(memory::RingBuffer* reader, uint32_t packet,
                                          uint32_t count, PacketExecutionMode mode);
  bool ExecutePacketType3_WAIT_REG_MEM(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_REG_RMW(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_REG_TO_MEM(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_MEM_WRITE(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_COND_WRITE(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_EVENT_WRITE(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_EVENT_WRITE_SHD(memory::RingBuffer* reader, uint32_t packet,
                                          uint32_t count);
  bool ExecutePacketType3_EVENT_WRITE_EXT(memory::RingBuffer* reader, uint32_t packet,
                                          uint32_t count);
  virtual bool ExecutePacketType3_EVENT_WRITE_ZPD(memory::RingBuffer* reader, uint32_t packet,
                                                  uint32_t count);
  bool ExecutePacketType3Draw(memory::RingBuffer* reader, uint32_t packet, const char* opcode_name,
                              uint32_t viz_query_condition, uint32_t count_remaining,
                              PacketExecutionMode mode);
  bool ExecutePacketType3_DRAW_INDX(memory::RingBuffer* reader, uint32_t packet, uint32_t count,
                                    PacketExecutionMode mode);
  bool ExecutePacketType3_DRAW_INDX_2(memory::RingBuffer* reader, uint32_t packet, uint32_t count,
                                      PacketExecutionMode mode);
  bool ExecutePacketType3_SET_CONSTANT(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_SET_CONSTANT2(memory::RingBuffer* reader, uint32_t packet,
                                        uint32_t count);
  bool ExecutePacketType3_LOAD_ALU_CONSTANT(memory::RingBuffer* reader, uint32_t packet,
                                            uint32_t count);
  bool ExecutePacketType3_SET_SHADER_CONSTANTS(memory::RingBuffer* reader, uint32_t packet,
                                               uint32_t count);
  bool ExecutePacketType3_IM_LOAD(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_IM_LOAD_IMMEDIATE(memory::RingBuffer* reader,

                                            uint32_t packet, uint32_t count);
  bool ExecutePacketType3_INVALIDATE_STATE(memory::RingBuffer* reader, uint32_t packet,
                                           uint32_t count);
  bool ExecutePacketType3_VIZ_QUERY(memory::RingBuffer* reader, uint32_t packet, uint32_t count);

  virtual Shader* LoadShader(xenos::ShaderType shader_type, uint32_t guest_address,
                             const uint32_t* host_address, uint32_t dword_count) = 0;

  virtual bool IssueDraw(xenos::PrimitiveType prim_type, uint32_t index_count,
                         IndexBufferInfo* index_buffer_info, bool major_mode_explicit) = 0;
  virtual bool IssueCopy() = 0;

  // "Actual" is for the command processor thread, to be read by the
  // implementations.
  SwapPostEffect GetActualSwapPostEffect() const { return swap_post_effect_actual_; }

  // Opens the trace and runs the complete backend initialization hook as one
  // fail-closed operation. Failed initialization discards the partial file and
  // disarms the request instead of retrying every command buffer.
  bool OpenAndInitializeTrace(const std::filesystem::path& path, uint32_t title_id);
  bool ExecutePacketSpan(uint32_t ptr, uint32_t count, PacketExecutionMode mode);
  void RequestFrameTraceOnThread(const std::filesystem::path& root_path);
  void BeginTracingOnThread(const std::filesystem::path& root_path);
  void EndTracingOnThread();
  void MarkTraceInitializationIncomplete() { trace_initialization_incomplete_ = true; }
  virtual void InitializeTrace();

  // Shared readback resolve mode with backend legacy-flag alias support.
  ReadbackResolveMode GetReadbackResolveMode(bool legacy_readback_resolve_enabled) const;
  // Shared memexport readback enable state with backend legacy-flag override support.
  bool IsReadbackMemexportEnabled(bool legacy_backend_flag) const;

  memory::Memory* memory_ = nullptr;
  system::KernelState* kernel_state_ = nullptr;
  GraphicsSystem* graphics_system_ = nullptr;
  RegisterFile* register_file_ = nullptr;

  TraceWriter trace_writer_;
  enum class TraceState {
    kDisabled,
    kStreaming,
    kSingleFrame,
  };
  TraceState trace_state_ = TraceState::kDisabled;
  std::filesystem::path trace_stream_path_;
  std::filesystem::path trace_frame_path_;
  bool trace_initialization_incomplete_ = false;
  // The native GoldenEye bridge may execute direct packet spans outside the
  // command worker. Trace controls take this gate exclusively, so opening or
  // finalizing a capture can't overtake a span that started before the request.
  // Packet spans share it, preserving the normal no-capture concurrency.
  std::shared_mutex trace_lifecycle_mutex_;
  // While capture is requested or active, packet spans must also be mutually
  // exclusive because they all emit into the same ordered FILE stream.
  std::mutex trace_execution_mutex_;
  std::atomic<bool> trace_capture_active_{false};

  std::atomic<bool> worker_running_;
  system::object_ref<system::XHostThread> worker_thread_;

  mutable std::mutex pending_fns_mutex_;
  // Guarded by pending_fns_mutex_. Shutdown closes this gate before changing
  // worker_running_, so every function reported as accepted is drained before
  // the worker exits.
  bool worker_accepting_functions_ = false;
  std::queue<std::function<void()>> pending_fns_;
  std::atomic<bool> worker_paused_{false};
  // Pause blocks until its worker callback has established the pause. Keep a
  // concurrent Resume from overtaking that callback and leaving the worker
  // paused after the public state has already changed back to running.
  std::mutex pause_mutex_;

  // MicroEngine binary from PM4_ME_INIT
  std::vector<uint32_t> me_bin_;

  std::atomic<uint32_t> counter_{0};
  std::atomic<uint32_t> swap_counter_{0};

  CommandRingState ring_state_;

  std::unique_ptr<rex::thread::Event> write_ptr_index_event_;

  // Some titles submit writes beyond the emulated register file range in PM4
  // packets. Preserve these values so dependent packet logic can still observe
  // them instead of dropping the write entirely.
  std::unordered_map<uint32_t, uint32_t> extended_register_values_;

  uint64_t bin_select_ = 0xFFFFFFFFull;
  uint64_t bin_mask_ = 0xFFFFFFFFull;

  Shader* active_vertex_shader_ = nullptr;
  Shader* active_pixel_shader_ = nullptr;

  std::atomic<bool> paused_{false};

  // By default (such as for tools), post-processing is disabled.
  // "Desired" is for the external thread managing the post-processing effect.
  SwapPostEffect swap_post_effect_desired_ = SwapPostEffect::kNone;
  SwapPostEffect swap_post_effect_actual_ = SwapPostEffect::kNone;

  // Set by backend command processors to their legacy memexport readback cvar
  // name (for explicit-override compatibility).
  const char* legacy_readback_memexport_cvar_name_ = nullptr;

 private:
  reg::DC_LUT_30_COLOR gamma_ramp_256_entry_table_[256] = {};
  reg::DC_LUT_PWL_DATA gamma_ramp_pwl_rgb_[128][3] = {};
  uint32_t gamma_ramp_rw_component_ = 0;
};

}  // namespace rex::graphics
